### ISSUE TITLE
Incomplete Input error when registering device

### ISSUE THREAD

**Issue by Glitch482** [tesla-android/tesla-android-os#1]
Can't seem to get past step #13 in registering the device - has failed with multiple attempts, keep getting an "incomplete input" message in terminal.

C:\Users\Rogue\Desktop\tesla-android-2022.18.1> .\adb shell 'sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "select * from main where name = \"android_id\";"'
Error: incomplete input
C:\Users\Rogue\Desktop\tesla-android-2022.18.1>

**Comment by jan-siroky** [comment]
Looks like you are missing backslashes before double quotes on string "android_id"
-->`\"android_id\"`<--

**Comment by Glitch482** [comment]
Thanks for replying. 

The slashes were used, but the forum is stripping them out when posting 

`PS C:\Users\Rogue\Desktop\tesla-android-2022.18.1> .\adb shell 'sqlite3 /data/data/com.google.android.gsf/databases/gservices.db "select * from main where name = \"android_id\";"'
Error: incomplete input
PS C:\Users\Rogue\Desktop\tesla-android-2022.18.1>`

**Comment by Glitch482** [comment]
Was able to obtain the GSF ID by following the steps listed here 

https://forum.xda-developers.com/t/guide-to-avoid-registering-a-new-gsf-android_id-at-each-clean-install.3772123/

**Comment by mikegapinski** [comment]
Device registration with google is not needed starting with version 2022.25.1
