### ISSUE TITLE
why need blocking hosts?

### ISSUE THREAD

**Issue by ssdasdas** [tesla-android/tesla-android-os#10]
what is it?
/src/modules/tesla-android/filesystem/etc/pihole/custom.list

**Comment by mikegapinski** [comment]
Base for offline mode - teslas send a few requests each time they connect to Wi-Fi. If they don’t get a 200 with a specific response headers Wi-Fi connection is automatically terminated

**Comment by ssdasdas** [comment]
This may prevent tesla update

**Comment by mikegapinski** [comment]
No it does not, I’ve tested this with multiple updates
